services:
  postgresql:
    container_name: postgresql
    image: postgres:alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: "128M"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jaeger-service:
    container_name: jaeger-service
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: "64M"
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      COLLECTOR_OTLP_ENABLED: true

  frontend-service:
    container_name: frontend-service
    build:
      context: ./authentication_page_service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PWD_SERVICE: http://auth-service:8080
      APP_SERVICE_URL: https://www.microsoft.com
    ports:
      - "3000:3000"

  pwd-hashing-service:
    container_name: pwd-hashing-service
    build:
      context: ./hashing_service
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.15
          memory: "32M"
    environment:
      RUST_BACKTRACE: 1
      OTLP_ENDPOINT: http://jaeger-service:4317
      PORT: "8820"
    ports:
      - "8820:8820"

  auth-service:
    container_name: auth-service
    build:
      context: ./jwt_authentication_service
      dockerfile: ./src/main/docker/Dockerfile
    restart: unless-stopped
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgrespw
      DB_HOST: postgresql
      SALT_SERVICE: http://pwd-hashing-service:8820
      OTLP_ENDPOINT: http://jaeger-service:4317
    ports:
      - "8810:8810"


volumes:
  postgres_data: