services:
  frontend:
    container_name: frontend
    build:
      context: ./authentication_page_service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
  password_encryption:
    container_name: password_encryption
    build:
      context: ./hashing_service
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.15
          memory: "32M"
    environment:
      RUST_BACKTRACE: 1
      OTLP_ENDPOINT: http://jaeger:4317
      PORT: "8810"
    ports:
      - "8810:8810"
  jwt_auth:
    container_name: jwt_auth
    build:
      context: ./jwt_authentication_service
      dockerfile: ./src/main/docker/Dockerfile
    restart: unless-stopped
    environment:
      JAEGER_HOST: http://jaeger:4317
    ports:
      - "8080:8080"
  postgresql:
    container_name: database-postgresql
    build:
      context: ./postgresql_docker
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: "128M"
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: "64M"
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      COLLECTOR_OTLP_ENABLED: true
