services:
  frontend:
    build:
      context: ./authentication_page_service
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
  password_encryption:
    build:
      context: ./hashing_service
      dockerfile: Dockerfile
    container_name: password_encryption
    restart: unless-stopped
    ports:
      - "8888:8888"
  jwt_auth:
    container_name: jwt_auth
    build:
      context: ./jwt_authentication_service
      dockerfile: src/main/docker/Dockerfile.native
    restart: unless-stopped
    ports:
      - "8080:8080"
