---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.name: jaeger-service
  name: jaeger-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.name: jaeger-service
  name: jaeger-service
spec:
  ports:
    - port: 16686
      targetPort: 16686
      protocol: TCP
      name: tcp-16686
      nodePort: 31001

    - port: 14268
      targetPort: 14268
      protocol: TCP
      name: tcp-14268

    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: tcp-4317

    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: tcp-4318

    - port: 14250
      targetPort: 14250
      protocol: TCP
      name: tcp-14250

  selector:
    app.name: jaeger-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.name: jaeger-service
  name: jaeger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: jaeger-service
  template:
    metadata:
      labels:
        app.name: jaeger-service
    spec:
      serviceAccountName: jaeger-service
      containers:
        - name: jaeger-service
          image: jaegertracing/all-in-one:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.25"
              memory: "64Mi"
            requests:
              cpu: "0.25"
              memory: "64Mi"
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
