---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.name: pwd-hashing-service
  name: pwd-hashing-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.name: pwd-hashing-service
  name: pwd-hashing-service
spec:
  ports:
    - port: 8820
      targetPort: 8820
      name: tcp-8820
  selector:
    app.name: pwd-hashing-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.name: pwd-hashing-service
  name: pwd-hashing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: pwd-hashing-service
  template:
    metadata:
      labels:
        app.name: pwd-hashing-service
    spec:
      containers:
        - name: pwd-hashing-service
          image: ghcr.io/chatgut/authentication-hashing-salting:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.15"
              memory: "16Mi"
          env:
            - name: PORT
              value: "8820"
            - name: RUST_BACKTRACE
              value: "1"
            - name: OTLP_ENDPOINT
              value: http://jaeger-service:4317
          ports:
            - containerPort: 8820
              name: http
              protocol: TCP
